---
name: loki

instance_groups:
  - name: loki
    azs:
      - z1
    instances: 1
    persistent_disk: 10_240
    jobs:
      - name: loki
        release: loki
        provides:
          loki: {as: loki, shared: true}
        properties:
          loki:
            tls: false
            auth:
              enabled: false
            server:
              http_listen_address: localhost
              http_listen_port: 3100
            index:
              storage: boltdb
            object_store:
              storage: filesystem
            validation:
              enforce_metric_name: false
              reject_old_samples: true
              reject_old_samples_max_age: 672h
            retention:
              period: "168h"
    networks:
      - name: cf
    stemcell: default
    vm_type: vm_2cpu_4gb

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-jammy
    version: "1.83"

releases:
- name: loki
  version: 0+dev.1
  sha1: 507e71c+
